version: "3.7"
services:
  n8n:
    container_name: n8n
    build:
      context: .
      dockerfile: Dockerfile   
    ports:
      - 5678:5678
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_HOST=n8n-fjrp.onrender.com 
      - N8N_PORT=5678                     
      - N8N_PROTOCOL=https                         
      - N8N_RUNNERS_ENABLED=true 
      - NODE_ENV=production      
      - WEBHOOK_URL=https://n8n-fjrp.onrender.com
      - TZ=America/Sao_Paulo 
      - GENERIC_TIMEZONE=America/Sao_Paulo 
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    logging:
      options:
        max-size: 100M

volumes:
  n8n_data:
    name: n8n_data