FROM docker.n8n.io/n8nio/n8n:1.88.0

ENV N8N_HOST=n8n-9d1u.onrender.com
ENV N8N_PORT=5678
ENV N8N_PROTOCOL=https
ENV N8N_RUNNERS_ENABLED=true
ENV NODE_ENV=production
ENV WEBHOOK_URL=https://n8n-9d1u.onrender.com
ENV TZ=America/Sao_Paulo
ENV GENERIC_TIMEZONE=America/Sao_Paulo
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

# URL esperada = https://n8n-9d1u.onrender.com/rest/oauth2-credential/callback

VOLUME ["/home/node/.n8n"]