version: "3.7"
services:
  n8n:
    container_name: n8n
    build:
      context: .
      dockerfile: Dockerfile   
    ports:
      - 5678:5678
    volumes:
      - n8n_data:/home/node/.n8n
    logging:
      options:
        max-size: 100M

volumes:
  n8n_data:
    name: n8n_data